.TH RAPIDDISK 1 "Oct 16 2010" "Linux" "GENERAL COMMANDS"
.SH NAME
rapiddisk \- An administration tool to manage the RapidDisk RAM disk devices and RapidDisk-Cache mappings.
.SH SYNOPSIS
rapiddisk [ -h | -v ] function [ parameters ]
.SH DESCRIPTION
rapiddisk is a RapidDisk module management tool to manage RapidDisk RAM disk devices. Dynamically create, remove, resize RAM volumes and if desired, map or unmap them as a cache volume to any block device.
.SS Options
.TP
-h
Invoke the help menu.
.TP
-v
Display the version number.
.SS Functions
.TP
-a
Attach RAM disk device (size in MBytes).
.TP
-b
Backend block device absolute path (for cache mapping).
.TP
-c
Input capacity for size or resize of RAM disk device (in MBytes).
.TP
-d
Detach RAM disk device.
.TP
-e
Export a RapidDisk block device as an NVMe Target.
.TP
-f
Erase all data to a specified RapidDisk device (dangerous).
.TP
-H
The host to export / unexport the NVMe Target to / from.
.TP
-j
Enable JSON formatted output.
.TP
-l
List all attached RAM disk devices.
.TP
-m
Map an RapidDisk device as a caching node to another block device.
.TP
-P
The port to export / unexport the NVMe Target to / from.
.TP
-p
Define cache policy: write-through (wt), write-around (wa) or writeback (wb) (dangerous) (default: write-through).
Writeback caching is supplied by the dm-writecache kernel module and is not intended for production use as it may result in data loss on hardware/power failure.
.TP
-r
Dynamically grow the size of an existing RapidDisk device.
.TP
-s
Obtain RapidDisk-Cache Mappings statistics.
.TP
-u
Unmap a RapidDisk device from another block device.
.TP
-v
Display the utility version string.
.TP
-x
Unexport a RapidDisk block device from an NVMe Target.
.SS Parameters (if applicable)
.TP
[size]
Specify desired size of attaching RAM disk device in MBytes.
.TP
[mode]
Write Through (wt) or Write Around (wa) for cache.
.SH EXAMPLE USAGE
.TP
rapiddisk -l
.TP
rapiddisk -l -j
.TP
rapiddisk -a 64
.TP
rapiddisk -d rd2
.TP
rapiddisk -r rd2 -c 128
.TP
rapiddisk -m rd1 -b /dev/sdb
.TP
rapiddisk -m rd1 -b /dev/sdb -p wt
.TP
rapiddisk -m rd3 -b /dev/mapper/rc-wa_sdb -p wb
.TP
rapiddisk -u rc-wt_sdb
.TP
rapiddisk -s rc-wt_sdb
.TP
rapiddisk -f rd2
.TP
rapiddisk -e -b rd3 -P 1 -H nqn.host1
.TP
rapiddisk -x -b rd3 -P 1 -H nqn.host1
.SH EXIT STATUS
rapiddisk returns a zero exit status if no error occurs during operation. A non-zero value is returned on error.
.SH AUTHORS
Original version: Petros Koutoupis (petros@petroskoutoupis.com)
.SH SEE ALSO
View the RapidDisk project page: http://www.rapiddisk.org
