.TH RAPIDDISK 1 "Oct 16 2010" "Linux" "GENERAL COMMANDS"
.SH NAME
rapiddisk \- An administration tool to manage the RapidDisk RAM disk devices and RapidDisk-Cache mappings.
.SH SYNOPSIS
rapiddisk [ -h | -v ] function [ parameters: unit | size | src & dest | cache & source | mode ]
.SH DESCRIPTION
rapiddisk is a RapidDisk module management tool. The tool allows the user to list all attached RapidDisk devices, with the ability to dynamically attach a new RapidDisk block devices and detach existing ones. It also is capable of mapping and unmapping an RapidDisk volumes as a Write-Through or Write Around cache to any block device via the RapidDisk-Cache kernel module.
.SS Options
.TP
-h | --help
Invoke the help menu.
.TP
-v | --version
Display the version number.
.SS Functions
.TP
--attach
Dynamically attach new RapidDisk devices.
.TP
--detach
Dynamically detach RapidDisk devices.
.TP
--list
List all attached RapidDisk devices.
.TP
--list-json
List all attached RapidDisk devices in JSON format (only if enabled during compilation).
.TP
--short-list   
List all attached RapidDisk devices in script friendly format.
.TP
--flush
Erase all data to a specified RapidDisk device (dangerous).
.TP
--resize
Dynamically grow the size of an existing RapidDisk device.
.TP
--archive
Using zlib, archive an RapidDisk device to a data file.
.TP
--restore
Using zlib, restore an RapidDisk device from an archived data file.
.TP
--cache-map
Map an RapidDisk device as a caching node to another block device.
.TP
--cache-unmap
Map an RapidDisk device as a caching node to another block device.
.TP
--stat-cache
Obtain RapidDisk-Cache Mappings statistics.
.TP
--enable-crypt
Initialize a storage volume for data encryption. Please store user defined keys in /etc/rapiddisk/key, otherwise it will default to the built-in DES key provided by the utility (only if enabled during compilation).
.TP
--activate-crypt
Activate an encryption volume. Please store user defined keys in /etc/rapiddisk/key, otherwise it will default to the built-in DES key provided by the utility (only if enabled during compilation).
.TP
--deactivate-crypt
Deactivate an encrypted volume (only if enabled during compilation).
.SS Parameters (if applicable)
.TP
[size]
Specify desired size of attaching RAM disk device in MBytes.
.TP
[unit]
Specify unit number of RAM disk device to detach.
.TP
[src]
Source path for archive/restore options.
.TP
[dest]
Destination path for arcive/restore options.
.TP
[cache]
Specify RapidDisk node to use as caching volume.
.TP
[source]
Specify block device to map cache to.
.TP
[mode]
Write Through (wt) or Write Around (wa) for cache.
.SH EXAMPLE USAGE
.TP
rapiddisk --list
.TP
rapiddisk --list-json
.TP
rapiddisk --attach 64
.TP
rapiddisk --detach rd2
.TP
rapiddisk --resize rd2 128
.TP
rapiddisk --archive rd0 rd-052911.dat
.TP
rapiddisk --restore rd-052911.dat rd0
.TP
rapiddisk --cache-map rd1 /dev/sdb
.TP
rapiddisk --cache-map rd1 /dev/sdb wt
.TP
rapiddisk --cache-unmap rc_sdb
.TP
rapiddisk --stat-cache rc_sdb
.TP
rapiddisk --flush rd2
.TP
rapiddisk --enable-crypt /dev/rd0
.TP
rapiddisk --activate-crypt /dev/rd0
.TP
rapiddisk --deactivate-crypt /dev/mapper/crypt-rd0
.SH EXIT STATUS
rapiddisk returns a zero exit status if no error occurs during operation. A non-zero value is returned on error.
.SH AUTHORS
Original version: Petros Koutoupis (petros@petroskoutoupis.com)
.SH SEE ALSO
View the RapidDisk project page: http://www.rapiddisk.org
