#!/bin/sh
PREREQ=""
prereqs()
{
	echo "$PREREQ"
}

case $1 in
	prereqs)
		prereqs
		exit 0
		;;
esac

. /scripts/functions

# Begin real processing below this line
if [ -x /sbin/rapiddisk_sub ] ; then
	/sbin/rapiddisk_sub
fi

exit 0
