#!/bin/sh
PREREQ=""
prereqs()
{
        echo "$PREREQ"
}

case $1 in
        prereqs)
                prereqs
                exit 0
                ;;
esac

. /scripts/functions

# Begin real processing below this line

cache="$(rapiddisk -l)"
ramdisks="$(echo $cache | grep -oE 'RapidDisk Device +[[:digit:]]+: +[^ ]+'|grep -oE '[^ ]+$')"
mapped="$(echo $cache | grep -oE 'Cache: +[^ ]+'| grep -oE '[^ ]+$')"
for map in $mapped ; do
	for rd in $ramdisks ; do
		if [ $map = $rd ]; then
			tokeep="$tokeep $rd"
		fi
	done
done
for rd in $ramdisks; do
	for rmv in $tokeep ; do
		if [ ! $rd = $rmv ] ; then
			removelist="$removelist $rd"
		fi
	done
done

for remove in $removelist ; do
	if rapiddisk 2>&1 -d $remove ; then
	  log_warning_msg "rapiddisk: deleted $remove ramdisk"
	else
	  log_warning_msg "rapiddisk: failed to delete $remove ramdisk"
  fi
done
exit 0

