#!/bin/sh
# prerm script for midas
#
# see: dh_installdeb(1)

set -e

. /usr/share/debconf/confmodule

# Source dbconfig-common functions
if [ -f /usr/share/dbconfig-common/dpkg/prerm.pgsql  ]; then
  . /usr/share/dbconfig-common/dpkg/prerm.pgsql
fi

case "$1" in
  remove|upgrade|deconfigure)
    dkms remove -m rapiddisk -v 5.2 --all
  ;;

  failed-upgrade)
  ;;

  *)
    echo "prerm called with unknown argument \`$1'" >&2
    exit 1
  ;;
esac

exit 0
