#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

# Begin real processing below this line
if [ -x /usr/sbin/rapiddisk_sub ] ; then
	/usr/sbin/rapiddisk_sub
fi

exit 0
