#!/bin/sh

PREREQ="lvm2"

prereqs()
{
	echo "$PREREQ"
}

case $1 in
	prereqs)
		prereqs
		exit 0
		;;
esac

. /scripts/functions

# Begin real processing below this line
if [ -x /usr/sbin/rapiddisk_sub ] ; then
	/usr/sbin/rapiddisk_sub
fi

exit 0
