#!/bin/sh
PREREQ=""
prereqs()
{
	echo "$PREREQ"
}

case "${1}" in
prereqs)
	prereqs
	exit 0
	;;
esac

# Begin real processing below this line

modprobe -v rapiddisk
modprobe -v rapiddisk-cache

rapiddisk --attach RAMDISKSIZE
rapiddisk --cache-map rd0 BOOTDEVICE wa
rapiddisk --list

exit 0

