#!/bin/sh
PREREQ=""
prereqs()
{
	echo "$PREREQ"
}

case "${1}" in
prereqs)
	prereqs
	exit 0
	;;
esac

. /usr/share/initramfs-tools/hook-functions

# Begin real processing below this line

manual_add_modules rapiddisk
manual_add_modules rapiddisk-cache
copy_exec /sbin/rapiddisk /sbin

exit 0

