#!/bin/sh
PREREQ=""
prereqs()
{
	echo "$PREREQ"
}

case "${1}" in
prereqs)
	prereqs
	exit 0
	;;
esac

# Begin real processing below this line

if [ -x /usr/sbin/rapiddisk_KERNELVERSION ] ; then
	modprobe -v rapiddisk
	modprobe -v rapiddisk-cache

	rapiddisk_KERNELVERSION --attach RAMDISKSIZE
	rapiddisk_KERNELVERSION --cache-map rd0 BOOTDEVICE wa
fi

exit 0

