#!/bin/sh
PREREQ=""
prereqs()
{
	echo "$PREREQ"
}

case "${1}" in
prereqs)
	prereqs
	exit 0
	;;
esac

. /usr/share/initramfs-tools/hook-functions

# Begin real processing below this line
if [ "$version" = "KERNELVERSION" ] ; then
	manual_add_modules rapiddisk
	manual_add_modules rapiddisk-cache
	copy_exec /sbin/rapiddisk /sbin/rapiddisk_KERNELVERSION
fi

exit 0

